server:
  port: 3200

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/currency-converter
    username: currency-converter
    password: currency-converter
  jpa:
    hibernate:
      ddl-auto: update

api:
  baseUrl: "https://economia.awesomeapi.com.br"